# Generated by Django 4.2 on 2023-04-12 05:57

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_managers_ourpartner_projects_teachers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('school', models.CharField(default='', max_length=250)),
            ],
            options={
                'verbose_name': 'Обратный звонок',
                'verbose_name_plural': 'Обратный звонок',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insta', models.CharField(blank=True, default='', max_length=254, null=True, verbose_name='Ссылка на инстаграм')),
                ('image', models.ImageField(upload_to='contacts/')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.CharField(default='', max_length=254, verbose_name='Телефон')),
                ('address', models.CharField(default='', max_length=254, verbose_name='Адрес')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='server.contact')),
            ],
            options={
                'verbose_name': 'Контакты Translation',
                'db_table': 'server_contact_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
