# Generated by Django 4.2 on 2023-04-12 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_callback_contact_contacttranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='image',
        ),
    ]
